name: Github pages deployer

# Run this workflow every time a new commit pushed to your repository
on:
  push:
    branches:
      - master

jobs:
  # Set the job key. The key is displayed as the job name
  # when a job name is not provided
  gh-pages:
    # Name the Job
    name: Deploy to Github pages
    # Set the type of machine to run on
    runs-on: ubuntu-latest

    steps:
      # Checks out a copy of your repository on the ubuntu-latest machine
      - name: Checkout code ðŸ›Žï¸
        uses: actions/checkout@v2
        with:
          persist-credentials: false

      - name: Install tailwind
        run: cd tailwind && npm install tailwindcss@2.1.2 --no-save

      - name: Build ðŸ”§
        run: |
          cd tailwind
          cat tailwind.css custom.css > tailwind.temp.css
          npx tailwindcss build tailwind.temp.css -c tailwind.config.prod.js | npx clean-css-cli > build.css

      - name: Remove dev css links
        run: |
          sed -i 's|<link href="tailwind/custom.css" rel="stylesheet">||g' *.html
          sed -i "s|tailwind/build.css|tailwind/build.css?v=$(git log --format="%h" -n 1)|g" *.html

      - name: Deploy ðŸš€
        uses: JamesIves/github-pages-deploy-action@3.7.1
        with:
          BRANCH: gh-pages
          FOLDER: . # The folder the action should deploy.
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SINGLE_COMMIT: true
          PRESERVE: true
